spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: sharding-sphere-jdbc-demo

server:
  port: 12800